# -*- coding: utf-8 -*-
"""Streamlit_THT_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZuZTlpl9dlEuD28RrmnCBf1oGY2m96J
"""

import streamlit as st
import pandas as pd

# --- PAGE CONFIGURATION ---
st.set_page_config(
   page_title="Delivery Time Analysis Dashboard",
   layout="wide",
   initial_sidebar_state="expanded",
)

# --- DATA LOADING ---
@st.cache_data
def load_data():
    """Loads the dataset"""
    df = pd.read_csv('FDT_cleaned.csv')
    # Drop rows with missing values for simplicity in this demo
    df.dropna(inplace=True)
    return df

df = load_data()

st.title("🚚 Delivery Time Analysis Dashboard")
st.markdown("""
This dashboard provides insights into delivery performance metrics and factors affecting delivery times.
Explore how different variables like weather conditions, traffic levels, vehicle types, and courier experience impact delivery efficiency.
""")

# --- SIDEBAR FOR FILTERS ---
st.sidebar.header("Filter Data")

# Filter for weather
weather_types = st.sidebar.multiselect(
    "Select Weather Conditions",
    options=df["Weather"].unique(),
    default=df["Weather"].unique()
)

# Filter for traffic level
traffic_levels = st.sidebar.multiselect(
    "Select Traffic Levels",
    options=df["Traffic_Level"].unique(),
    default=df["Traffic_Level"].unique()
)

# Filter for time of day
time_of_day = st.sidebar.multiselect(
    "Select Time of Day",
    options=df["Time_of_Day"].unique(),
    default=df["Time_of_Day"].unique()
)

# Filter for vehicle type
vehicle_types = st.sidebar.multiselect(
    "Select Vehicle Types",
    options=df["Vehicle_Type"].unique(),
    default=df["Vehicle_Type"].unique()
)

# Filter for distance range
min_distance, max_distance = float(df["Distance_km"].min()), float(df["Distance_km"].max())
distance_range = st.sidebar.slider(
    "Select Distance Range (km)",
    min_value=min_distance,
    max_value=max_distance,
    value=(min_distance, max_distance)
)

# Filter for courier experience
min_exp, max_exp = float(df["Courier_Experience_yrs"].min()), float(df["Courier_Experience_yrs"].max())
exp_range = st.sidebar.slider(
    "Select Courier Experience Range (years)",
    min_value=min_exp,
    max_value=max_exp,
    value=(min_exp, max_exp)
)

# Filter for delivery time
min_delivery, max_delivery = float(df["Delivery_Time_min"].min()), float(df["Delivery_Time_min"].max())
delivery_range = st.sidebar.slider(
    "Select Delivery Time Range (minutes)",
    min_value=min_delivery,
    max_value=max_delivery,
    value=(min_delivery, max_delivery)
)

# --- FILTERING THE DATAFRAME ---
df_selection = df.copy()

# Apply filters
if weather_types:
    df_selection = df_selection[df_selection["Weather"].isin(weather_types)]
if traffic_levels:
    df_selection = df_selection[df_selection["Traffic_Level"].isin(traffic_levels)]
if time_of_day:
    df_selection = df_selection[df_selection["Time_of_Day"].isin(time_of_day)]
if vehicle_types:
    df_selection = df_selection[df_selection["Vehicle_Type"].isin(vehicle_types)]

# Apply range filters
df_selection = df_selection[
    (df_selection["Distance_km"] >= distance_range[0]) &
    (df_selection["Distance_km"] <= distance_range[1]) &
    (df_selection["Courier_Experience_yrs"] >= exp_range[0]) &
    (df_selection["Courier_Experience_yrs"] <= exp_range[1]) &
    (df_selection["Delivery_Time_min"] >= delivery_range[0]) &
    (df_selection["Delivery_Time_min"] <= delivery_range[1])
]

# Display error message if no data is selected
if df_selection.empty:
    st.warning("No data available for the selected filters. Please adjust your selection.")
    st.stop()

# --- MAIN PAGE CONTENT ---
st.subheader("📊 Key Delivery Metrics")

# --- DISPLAY KEY METRICS ---
col1, col2, col3, col4 = st.columns(4)
with col1:
    total_orders = df_selection.shape[0]
    st.metric(label="Total Orders", value=total_orders)
with col2:
    avg_delivery_time = round(df_selection["Delivery_Time_min"].mean(), 2)
    st.metric(label="Average Delivery Time (min)", value=avg_delivery_time)
with col3:
    avg_prep_time = round(df_selection["Preparation_Time_min"].mean(), 2)
    st.metric(label="Average Prep Time (min)", value=avg_prep_time)
with col4:
    avg_speed = round(df_selection["Speed"].mean(), 4)
    st.metric(label="Average Speed", value=avg_speed)

st.markdown("---")

# --- VISUALIZATIONS ---
st.subheader("📈 Delivery Performance Analysis")

# Arrange charts in columns
viz_col1, viz_col2 = st.columns(2)

with viz_col1:
    # Delivery time by weather
    st.subheader("Delivery Time by Weather Condition")
    weather_delivery = df_selection.groupby('Weather')['Delivery_Time_min'].mean().sort_values(ascending=False)
    st.bar_chart(weather_delivery)

with viz_col2:
    # Delivery time by traffic level
    st.subheader("Delivery Time by Traffic Level")
    traffic_delivery = df_selection.groupby('Traffic_Level')['Delivery_Time_min'].mean().sort_values(ascending=False)
    st.bar_chart(traffic_delivery)

# Second row of visualizations
viz_col3, viz_col4 = st.columns(2)

with viz_col3:
    # Delivery time by vehicle type
    st.subheader("Delivery Time by Vehicle Type")
    vehicle_delivery = df_selection.groupby('Vehicle_Type')['Delivery_Time_min'].mean().sort_values(ascending=False)
    st.bar_chart(vehicle_delivery)

with viz_col4:
    # Delivery time by time of day
    st.subheader("Delivery Time by Time of Day")
    time_delivery = df_selection.groupby('Time_of_Day')['Delivery_Time_min'].mean().sort_values(ascending=False)
    st.bar_chart(time_delivery)

# Third row of visualizations
viz_col5, viz_col6 = st.columns(2)

with viz_col5:
    # Preparation time analysis
    st.subheader("Preparation Time Distribution")
    prep_time_stats = df_selection.groupby('Vehicle_Type')['Preparation_Time_min'].mean().sort_values(ascending=False)
    st.bar_chart(prep_time_stats)

with viz_col6:
    # Speed analysis by vehicle type
    st.subheader("Average Speed by Vehicle Type")
    speed_by_vehicle = df_selection.groupby('Vehicle_Type')['Speed'].mean().sort_values(ascending=False)
    st.bar_chart(speed_by_vehicle)

# Performance statistics
st.subheader("📋 Performance Statistics")

col5, col6, col7, col8 = st.columns(4)
with col5:
    fastest_delivery = df_selection['Delivery_Time_min'].min()
    st.metric("Fastest Delivery", f"{fastest_delivery} min")
with col6:
    slowest_delivery = df_selection['Delivery_Time_min'].max()
    st.metric("Slowest Delivery", f"{slowest_delivery} min")
with col7:
    median_delivery = df_selection['Delivery_Time_min'].median()
    st.metric("Median Delivery Time", f"{median_delivery} min")
with col8:
    std_delivery = round(df_selection['Delivery_Time_min'].std(), 2)
    st.metric("Delivery Time Std Dev", f"{std_delivery} min")

# Courier experience analysis
st.subheader("👤 Courier Performance")

exp_col1, exp_col2, exp_col3 = st.columns(3)
with exp_col1:
    avg_experience = round(df_selection['Courier_Experience_yrs'].mean(), 2)
    st.metric("Average Courier Experience", f"{avg_experience} years")
with exp_col2:
    most_experienced = df_selection['Courier_Experience_yrs'].max()
    st.metric("Most Experienced Courier", f"{most_experienced} years")
with exp_col3:
    least_experienced = df_selection['Courier_Experience_yrs'].min()
    st.metric("Least Experienced Courier", f"{least_experienced} years")

# Additional insights
st.subheader("🔍 Additional Insights")

# Top 5 fastest deliveries
st.write("**Top 5 Fastest Deliveries:**")
fastest_deliveries = df_selection.nsmallest(5, 'Delivery_Time_min')[['Order_ID', 'Distance_km', 'Vehicle_Type', 'Weather', 'Delivery_Time_min']]
st.dataframe(fastest_deliveries, use_container_width=True)

# Top 5 slowest deliveries
st.write("**Top 5 Slowest Deliveries:**")
slowest_deliveries = df_selection.nlargest(5, 'Delivery_Time_min')[['Order_ID', 'Distance_km', 'Vehicle_Type', 'Weather', 'Delivery_Time_min']]
st.dataframe(slowest_deliveries, use_container_width=True)

# Weather impact analysis
st.write("**Weather Impact on Delivery:**")
weather_impact = df_selection.groupby('Weather').agg({
    'Delivery_Time_min': ['mean', 'median', 'count'],
    'Speed': 'mean'
}).round(3)
weather_impact.columns = ['Avg Delivery Time', 'Median Delivery Time', 'Order Count', 'Avg Speed']
st.dataframe(weather_impact.sort_values('Avg Delivery Time', ascending=False), use_container_width=True)

# Vehicle type efficiency
st.write("**Vehicle Type Efficiency:**")
vehicle_efficiency = df_selection.groupby('Vehicle_Type').agg({
    'Delivery_Time_min': ['mean', 'median'],
    'Speed': 'mean',
    'Distance_km': 'mean',
    'Order_ID': 'count'
}).round(3)
vehicle_efficiency.columns = ['Avg Delivery Time', 'Median Delivery Time', 'Avg Speed', 'Avg Distance', 'Order Count']
st.dataframe(vehicle_efficiency.sort_values('Avg Speed', ascending=False), use_container_width=True)

# --- DISPLAY DATA ---
with st.expander("View Filtered Data"):
    st.dataframe(df_selection)
    st.markdown(f"**Data Dimensions:** {df_selection.shape[0]} rows, {df_selection.shape[1]} columns")

    # Data summary
    st.write("**Data Summary:**")
    st.write(df_selection.describe())